include $(THEOS)/makefiles/common.mk

BUNDLE_NAME 					= grogeryprefs
grogeryprefs_FILES  			= GROGRootListController.m
grogeryprefs_FRAMEWORKS 		= UIKit
grogeryprefs_PRIVATE_FRAMEWORKS = Preferences
grogeryprefs_INSTALL_PATH 		= /Library/PreferenceBundles
grogeryprefs_CFLAGS 			= -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
